# Generated by Django 2.2.6 on 2019-10-05 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('order', models.IntegerField(db_index=True, verbose_name='order')),
                ('id', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'condition',
                'verbose_name_plural': 'conditions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.Condition', verbose_name='condition')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.Type', verbose_name='type')),
            ],
            options={
                'verbose_name': 'catalog',
                'verbose_name_plural': 'catalog',
                'ordering': ['type', 'condition'],
                'unique_together': {('type', 'condition')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='size')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.Catalog', verbose_name='catalog')),
            ],
            options={
                'verbose_name': 'inventory',
                'verbose_name_plural': 'inventory',
                'ordering': ['catalog__type', 'size', 'catalog__condition'],
                'unique_together': {('catalog', 'size')},
            },
        ),
    ]
