# Generated by Django 2.2.1 on 2019-05-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
                'ordering': ['id'],
            },
        ),
    ]
